### ISSUE TITLE
fix QInputDialog is not defined

### ISSUE THREAD

**Issue by RusAnonym** [soround/VKMusicDownloader#12]
![image](https://user-images.githubusercontent.com/45464902/179079305-096e18b0-00bc-4422-a10c-9023f7f8f821.png)
Ошибка происходит при входе в аккаунт с включённой 2FA
Для фикса надо [добавить импорт](https://stackoverflow.com/questions/42150905/pyqt5-nameerror)
Вместо:
https://github.com/soround/VKMusicDownloader/blob/6df906559dc887b6bca8a0878f63232d1be0499a/ui/mainwindow.py#L19
Так:
```python
from PyQt5.QtWidgets import QMessageBox, QFileDialog, QInputDialog
```

**Comment by soround** [comment]
Привет. Спасибо.
