### ISSUE TITLE
VKLightError (25): token confirmation required

### ISSUE THREAD

**Issue by irezni4uk** [soround/VKMusicDownloader#9]
Windows 7 x64
VKMusicDownloader 1.11.12
При нажатии "Загрузить список аудиозаписей" выдаёт ошибку: VKLightError (25): token confirmation required

**Comment by soround** [comment]
Это проблему можно исправить, заменив хост `api.vk.me`, на `api.vk.com`

**Comment by soround** [comment]
Эту проблему можно исправить, заменив хост `api.vk.me` на `api.vk.com`
